# This rule is not used by the deployment-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to deployments.kuberik.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deployment-controller
    app.kubernetes.io/managed-by: kustomize
  name: deployment-viewer-role
rules:
- apiGroups:
  - deployments.kuberik.com
  resources:
  - deployments
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deployments.kuberik.com
  resources:
  - deployments/status
  verbs:
  - get
