apiVersion: deployments.kuberik.com/v1alpha1
kind: GitHubDeployment
metadata:
  labels:
    app.kubernetes.io/name: github-controller
    app.kubernetes.io/managed-by: kustomize
  name: githubdeployment-sample
spec:
  # TODO(user): Add fields here
